### ISSUE TITLE
some more README feedback!

### ISSUE THREAD

**Issue by lbushra** [JeremyC497/Literally-Anything#2]
### Statement of the problem
I think that the problem statement should not be plural as of now since we are working with v0. 

### Recursive abstraction
Why is n > 1 and n < 4? Isn't it also possible to have only 1 step available or all 4 steps available to you?

### Base Case
We discussed in class three different base cases. I think the word "reached" implies that steps have been done beforehand when the base case should state when there are no possible moves to do, such as the explorer being on the treasure.

### Pseudocode
Again, I think this should focus on a smaller version of the problem. I think the wording of "one path" is a little confusing. When I first read it, I thought you were talking about different ways of solving the maze but when I reread it, I think you mean the next step that the explorer will take. Also, this is a little picky, but I think it would be more clear to say "the explorer" rather than "it".

_

Let me know if you disagree with any of my suggestions!

**Comment by Jiajie-Mai** [comment]
Although this comment is really late, I will still thank you for your advice. I understand that our README was severely lacking and even I was confused at some points. Your advice allowed me to understand the faults when writing the README.

Most of these problems have been resolved and accounted for.
